### ISSUE TITLE
fail to extract model 

### ISSUE THREAD

**Issue by assia-bourai** [vaclavcadek/keras2pmml#13]
hi, I'm tryin to extract the model in PMML file but an error appears which i don't know how to fix.
here is the code of my model:
`
import sys
import numpy
import theano
import os
import csv
import matplotlib.pyplot as plt
from tensorflow import keras 
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn import neighbors
from sklearn.model_selection import learning_curve, GridSearchCV
from sklearn import metrics
from imblearn.under_sampling import TomekLinks
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import model_from_json
from tensorflow.keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import *
from keras2pmml import keras2pmml

data2 = numpy.loadtxt('Data/Doctor/BuildData2.csv', delimiter=',')
X = data2[:,0:35].astype(theano.config.floatX)
Y = data2[:,35].astype(numpy.int32)
tl = TomekLinks()
X, Y = tl.fit_resample(X, Y)

# create model (in keras)
model = Sequential()
model.add(Dense(15, input_dim=35, activation='tanh'))
model.add(Dropout(0.2))
model.add(Dense(15, activation='tanh'))
model.add(Dropout(0.2))
model.add(Dense(1,  activation='sigmoid'))

# Compile model
model.compile(loss="binary_crossentropy",optimizer="adam", metrics=['accuracy'])

# Fit the model
model.fit(X, Y, validation_split=0.2, epochs=10, batch_size=10,verbose=2)

cv = KFold (X.shape[0])
score = model.evaluate(X, Y, verbose=0)

print("cross validation scores ",score )

keras2pmml(estimator = model, file = "Jpmml/NeuralNetwork_test22.pmml")

`

And the error that appears is: 

Traceback (most recent call last):
  File "NeuralNetwork - Copie.py", line 161, in <module>
    keras2pmml(estimator = model, file = "Jpmml/NeuralNetwork_test22.pmml")
  File "C:\Users\boura\AppData\Local\Programs\Python\Python36\lib\site-packages\keras2pmml\__init__.py", line 248, in keras2pmml
    feature_names, target_values = _validate_inputs(estimator, transformer, feature_names, target_values)
  File "C:\Users\boura\AppData\Local\Programs\Python\Python36\lib\site-packages\keras2pmml\__init__.py", line 54, in _validate_inputs
    for x in activations:
  File "C:\Users\boura\AppData\Local\Programs\Python\Python36\lib\site-packages\keras2pmml\__init__.py", line 21, in <lambda>
    return map(lambda x: x['config']['activation'], layers)
KeyError: 'activation'

In the beggining I hade the same problem as #10 , I have updated the library as suggested, but now I have the error mentionned above.
Can you help me please?

**Comment by vaclavcadek** [comment]
Hi, it's probably due to the incompatibility between this library and keras - as I'm not actively maintaining this library at the moment this could happen. 

What are the versions of keras2pmml and keras (e.g. from `pip freeze`)?
